const USER_COLLECTION = "users";
const RESUME_COLLECTION = "resumes";
const ORDERS_COLLECTION = "orders";
const PAYMENTS_COLLECTION = "payments";
const INVOICES_COLLECTION = "invoices";
const PRODUCTS_COLLECTION = "products";

export default {
  USER_COLLECTION,
  RESUME_COLLECTION,
  ORDERS_COLLECTION,
  PAYMENTS_COLLECTION,
  INVOICES_COLLECTION,
  PRODUCTS_COLLECTION,
};